python main.py --data hESC --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data hHEP --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data mDC --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 2048 >>  output_exp.txt
python main.py --data mESC --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data mHSC-E --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mHSC-GM --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 256 >>  output_exp.txt
python main.py --data mHSC-L --net STRING --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 64 >>  output_exp.txt
python main.py --data hESC --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data hHEP --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data mDC --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 128 >>  output_exp.txt
python main.py --data mESC --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 2048 >>  output_exp.txt
python main.py --data mHSC-E --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data mHSC-GM --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 256 >>  output_exp.txt
python main.py --data mHSC-L --net Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 128 >>  output_exp.txt
python main.py --data hESC --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data hHEP --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data mDC --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data mESC --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data mHSC-E --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mHSC-GM --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data mHSC-L --net Non-Specific --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 128 >>  output_exp.txt
python main.py --data mESC --net Lofgof --num 500 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data hESC --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data hHEP --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data mDC --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data mESC --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data mHSC-E --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mHSC-GM --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data mHSC-L --net STRING --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 64 >>  output_exp.txt
python main.py --data hESC --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data hHEP --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mDC --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 256 >>  output_exp.txt
python main.py --data mESC --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 2048 >>  output_exp.txt
python main.py --data mHSC-E --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mHSC-GM --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
python main.py --data mHSC-L --net Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 256 >>  output_exp.txt
python main.py --data hESC --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data hHEP --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 8192 >>  output_exp.txt
python main.py --data mDC --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 4096 >>  output_exp.txt
python main.py --data mESC --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 16384 >>  output_exp.txt
python main.py --data mHSC-E --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 2048 >>  output_exp.txt
python main.py --data mHSC-GM --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 1024 >>  output_exp.txt
python main.py --data mHSC-L --net Non-Specific --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 128 >>  output_exp.txt
python main.py --data mESC --net Lofgof --num 1000 --feature_type  exp --device 2 --use_deepimpute --batch_size 512 >>  output_exp.txt
