@echo off
python train_test_split.py --data hESC --net STRING --num 500 >> output.txt
python train_test_split.py --data hHEP --net STRING --num 500 >> output.txt
python train_test_split.py --data mDC --net STRING --num 500 >> output.txt
python train_test_split.py --data mESC --net STRING --num 500 >> output.txt
python train_test_split.py --data mHSC-E --net STRING --num 500 >> output.txt
python train_test_split.py --data mHSC-GM --net STRING --num 500 >> output.txt
python train_test_split.py --data mHSC-L --net STRING --num 500 >> output.txt
python train_test_split.py --data hESC --net Specific --num 500 >> output.txt
python train_test_split.py --data hHEP --net Specific --num 500 >> output.txt
python train_test_split.py --data mDC --net Specific --num 500 >> output.txt
python train_test_split.py --data mESC --net Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-E --net Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-GM --net Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-L --net Specific --num 500 >> output.txt
python train_test_split.py --data hESC --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data hHEP --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mDC --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mESC --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-E --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-GM --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mHSC-L --net Non-Specific --num 500 >> output.txt
python train_test_split.py --data mESC --net Lofgof --num 500 >> output.txt
python train_test_split.py --data hESC --net STRING --num 1000 >> output.txt
python train_test_split.py --data hHEP --net STRING --num 1000 >> output.txt
python train_test_split.py --data mDC --net STRING --num 1000 >> output.txt
python train_test_split.py --data mESC --net STRING --num 1000 >> output.txt
python train_test_split.py --data mHSC-E --net STRING --num 1000 >> output.txt
python train_test_split.py --data mHSC-GM --net STRING --num 1000 >> output.txt
python train_test_split.py --data mHSC-L --net STRING --num 1000 >> output.txt
python train_test_split.py --data hESC --net Specific --num 1000 >> output.txt
python train_test_split.py --data hHEP --net Specific --num 1000 >> output.txt
python train_test_split.py --data mDC --net Specific --num 1000 >> output.txt
python train_test_split.py --data mESC --net Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-E --net Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-GM --net Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-L --net Specific --num 1000 >> output.txt
python train_test_split.py --data hESC --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data hHEP --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mDC --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mESC --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-E --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-GM --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mHSC-L --net Non-Specific --num 1000 >> output.txt
python train_test_split.py --data mESC --net Lofgof --num 1000 >> output.txt
